apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-final-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-final-app
  template:
    metadata:
      labels:
        app: cicd-final-app
    spec:
      containers:
      - name: cicd-final-app
        image: python:3.9-slim
        command: ["python", "-c", "import time; print('App is running!'); while True: time.sleep(10)"]
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-final-app
spec:
  selector:
    app: cicd-final-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
