apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: oc-pipelines-oc-final-run-
spec:
  pipelineRef:
    name: oc-pipelines-oc-final
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipelinerun-pvc
